- name: variable on play level
  hosts: all
  vars: 
    URL: play.example.com 
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# Note: if we declare a variable in PLAY Level then all the tasks can access that variable        
- name: variable from file in play level
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# we can load all the variables from a file, since it is an play level, all the tasks can access those variables     

- name: variables on task level 
  hosts: all
  tasks:
    - name: Print URL in Task1
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task1.example.com

    - name: Print URL in Task2
      ansible.builtin.debug:
        msg: URL =={{URL}}
      vars:
        URL: task2.example.com